In [4]:
import pandas as pd
import openpyxl

In [15]:
wb = openpyxl.load_workbook(r'./data.xlsx') 
year_list = wb.sheetnames
year_list.reverse()
print(year_list)

df_1 = pd.read_excel('./data.xlsx', sheet_name='2009')
print(df_1)
name_list = df_1['City'].tolist()

['2009', '2010', '2011', '2012', '2013', '2014', '2014 Mid-Year', '2015', '2015 Mid-Year', '2016', '2016 Mid-Year', '2017', '2017 Mid-Year', '2018', '2018 Mid-Year', '2019', '2019 Mid-Year', '2020', '2020 Mid-Year', '2021 Mid-Year', '2022', '2022 Mid-Year', '2023']
    Rank                                City  Cost of Living Index  \
0      1                       Paris, France                 127.8
1      2                     Dublin, Ireland                 126.6
2      3                   Brussels, Belgium                 117.5
3      4                     Berlin, Germany                 115.2
4      5                   Stockholm, Sweden                 112.5
5      6                     Vienna, Austria                 109.5
6      7                        Milan, Italy                 109.4
7      8              Amsterdam, Netherlands                 108.5
8      9               Tel Aviv-Yafo, Israel                 106.8
9     10              London, United Kingdom                 106.6
10    11                        Lyon, France                 105.5
11    12                  Seoul, South Korea                 102.1
12    13                    Montreal, Canada                 101.8
13    14    San Francisco, CA, United States                 100.1
14    15         New York, NY, United States                 100.0
15    16                   Sydney, Australia                  99.5
16    17                    Lisbon, Portugal                  91.0
17    18                     Toronto, Canada                  80.4
18    19                     Santiago, Chile                  79.9
19    20                      Athens, Greece                  77.6
20    21                Singapore, Singapore                  74.7
21    22        Hong Kong, Hong Kong (China)                  74.5
22    23              Prague, Czech Republic                  74.2
23    24              Rio de Janeiro, Brazil                  70.5
24    25                    Belgrade, Serbia                  69.2
25    26                        Riga, Latvia                  68.8
26    27                       Amman, Jordan                  66.4
27    28          Johannesburg, South Africa                  64.7
28    29                   Budapest, Hungary                  63.8
29    30                 Guadalajara, Mexico                  63.2
30    31                    Bogota, Colombia                  58.5
31    32                     Manama, Bahrain                  58.0
32    33                      Warsaw, Poland                  54.9
33    34                     Shanghai, China                  52.6
34    35  Banja Luka, Bosnia And Herzegovina                  49.6
35    36                     La Paz, Bolivia                  46.7
36    37                        Delhi, India                  44.3
37    38                   Bangkok, Thailand                  39.9
38    39                Kiev (Kyiv), Ukraine                  36.8
39    40                         Pune, India                  34.9
40    41                     Dnipro, Ukraine                  34.8

    Rent Index  Cost of Living Plus Rent Index  Groceries Index  \
0         96.4                           115.4            117.0
1         87.6                           111.1            154.5
2         78.8                           102.2            110.9
3         33.0                            82.6             90.3
4         30.0                            79.8             99.0
5         62.7                            90.9             89.9
6         74.6                            95.6             96.1
7         84.0                            98.8             92.4
8         58.8                            87.8            110.5
9         93.6                           101.4             96.7
10        66.3                            90.0             75.6
11        34.7                            75.4            150.0
12        65.4                            87.4             87.8
13       117.6                           107.1            117.4
14       100.0                           100.0            100.0
15        65.0                            85.8            126.0
16        31.5                            67.4             52.7
17        59.5                            72.1            108.1
18        22.1                            56.9             55.4
19        36.4                            61.2             65.0
20       107.6                            87.7            110.8
21        58.1                            68.0             95.1
22        46.2                            63.1             63.8
23        32.6                            55.4             73.6
24        37.3                            56.5             51.0
25        43.5                            58.8             37.9
26        19.7                            47.9             88.7
27        44.6                            56.8             53.3
28        35.0                            52.4             56.5
29        28.5                            49.5             49.1
30        19.9                            43.2             61.0
31        82.4                            67.7             70.1
32        39.9                            49.0             42.7
33        45.9                            49.9             87.0
34        13.1                            35.1             58.8
35        21.8                            36.8             27.1
36        18.8                            34.1             28.7
37        24.5                            33.8             53.3
38        34.5                            35.9             29.1
39        11.0                            25.4             34.5
40        22.1                            29.7             25.7

    Restaurant Price Index  Local Purchasing Power Index
0                    116.5                          39.4
1                    131.6                          59.3
2                    107.6                          55.6
3                     79.2                          58.6
4                     85.2                          63.9
5                     80.6                          55.5
6                    105.8                          45.2
7                    116.3                          53.8
8                     67.2                          42.5
9                     92.2                          58.2
10                   120.0                          56.4
11                   102.7                          38.5
12                    62.9                          57.7
13                   105.2                         101.5
14                   100.0                         100.0
15                    88.0                          97.1
16                    66.4                          41.6
17                    57.7                          78.5
18                    40.8                          40.4
19                   100.5                          38.3
20                    91.1                          56.1
21                    88.7                          45.3
22                    54.7                          33.0
23                    51.8                          40.9
24                    58.6                          20.4
25                    49.3                          22.2
26                    62.0                          15.9
27                    40.8                          54.2
28                    44.8                          29.9
29                    69.5                          31.5
30                    44.3                          28.4
31                    67.2                          49.0
32                    50.4                          32.0
33                    44.0                          21.3
34                    36.0                          18.6
35                    37.2                          32.5
36                    36.2                          26.1
37                    25.3                          33.4
38                    36.8                          31.2
39                    22.0                          49.9
40                    37.3                          25.6

In [21]:
df_save = pd.DataFrame()
df_save['City'] = name_list

for year in year_list:
    df = pd.read_excel('./data.xlsx', sheet_name=year)
    index_dict = {}
    for i in range(len(df)):
        index_dict[df.loc[i, 'City']] = df.loc[i, 'Cost of Living Index']

    df_save[year] = 0
    for j in range(len(df_save)):
        df_save.loc[j, year] = index_dict.get(df_save.loc[j, 'City'])

print(df_save)

                                  City   2009   2010   2011   2012   2013  \
0                        Paris, France  127.8  130.3  112.0  113.9  125.0
1                      Dublin, Ireland  126.6  120.8  118.2  119.6  121.5
2                    Brussels, Belgium  117.5  120.0  111.5  109.1  111.6
3                      Berlin, Germany  115.2  115.2   84.6   89.1   86.6
4                    Stockholm, Sweden  112.5  111.0  104.8  109.1  127.0
5                      Vienna, Austria  109.5  103.9  105.9  101.5   99.5
6                         Milan, Italy  109.4  122.6  103.9   96.9  106.1
7               Amsterdam, Netherlands  108.5  111.3  114.2  110.8  107.6
8                Tel Aviv-Yafo, Israel  106.8   94.0    NaN    NaN   96.9
9               London, United Kingdom  106.6  118.5  105.1  118.5  116.1
10                        Lyon, France  105.5  115.0   99.4   91.1  104.1
11                  Seoul, South Korea  102.1   88.6   66.7   70.5   84.4
12                    Montreal, Canada  101.8   85.3   89.1   97.9   91.6
13    San Francisco, CA, United States  100.1   90.6   88.1  102.5   96.5
14         New York, NY, United States  100.0  100.0  100.0  100.0  100.0
15                   Sydney, Australia   99.5  104.8  113.1  132.4  139.2
16                    Lisbon, Portugal   91.0   85.4   74.6   76.3   78.7
17                     Toronto, Canada   80.4   83.4   91.6  104.5  103.7
18                     Santiago, Chile   79.9   70.7   64.7   69.9   68.9
19                      Athens, Greece   77.6   71.4   93.1   96.5   96.1
20                Singapore, Singapore   74.7   65.9   88.8   96.1  106.3
21        Hong Kong, Hong Kong (China)   74.5   68.0   79.3   88.1   84.4
22              Prague, Czech Republic   74.2   72.1   64.2   62.9   65.7
23              Rio de Janeiro, Brazil   70.5   73.7   86.1   91.8   86.1
24                    Belgrade, Serbia   69.2   66.8   59.9   56.2   57.2
25                        Riga, Latvia   68.8   68.2   73.2   70.8   69.9
26                       Amman, Jordan   66.4   65.6   63.3   66.0   67.9
27          Johannesburg, South Africa   64.7   61.1   70.3   74.2   67.4
28                   Budapest, Hungary   63.8   63.7   63.1   63.4   64.4
29                 Guadalajara, Mexico   63.2   50.8   52.0   57.7   54.6
30                    Bogota, Colombia   58.5   54.4   56.0   69.5   64.7
31                     Manama, Bahrain   58.0   55.0    NaN   71.9   90.5
32                      Warsaw, Poland   54.9   53.9   57.2   53.6   61.5
33                     Shanghai, China   52.6   53.2   55.9   54.2   73.6
34  Banja Luka, Bosnia And Herzegovina   49.6   49.0   51.3   50.1   50.6
35                     La Paz, Bolivia   46.7   39.8   39.0    NaN    NaN
36                        Delhi, India   44.3   32.4   36.8   37.9   35.1
37                   Bangkok, Thailand   39.9   36.6   44.3   52.6   60.7
38                Kiev (Kyiv), Ukraine   36.8   33.8   50.4   59.9   53.2
39                         Pune, India   34.9   32.6   29.0   31.9   32.3
40                     Dnipro, Ukraine   34.8   33.8    NaN    NaN    NaN

     2014  2014 Mid-Year   2015  2015 Mid-Year  ...   2018  2018 Mid-Year  \
0   120.7          117.1   99.6           84.5  ...   92.9           84.7
1   111.5          110.9   95.6           83.8  ...   89.9           80.3
2   103.8          105.8   92.8           82.4  ...   83.6           75.7
3    84.5           84.5   74.7           67.0  ...   74.3           67.7
4   113.9          106.2   89.1           82.1  ...   90.8           77.2
5    90.2           86.7   77.0           68.1  ...   78.6           70.9
6   100.4           97.6   83.7           74.4  ...   85.1           73.9
7   100.0          101.0   88.2           79.3  ...   89.1           82.1
8    98.5           98.5   85.5           83.4  ...   90.4           77.4
9   113.3          117.0  105.8          101.7  ...   88.7           81.3
10  104.1          103.6   92.0           79.0  ...   84.5           78.0
11   92.7           94.8   83.7           82.5  ...   87.6           82.0
12   83.3           85.2   81.1           73.5  ...   69.2           63.5
13   93.7           95.9   97.0          100.3  ...   97.8           96.9
14  100.0          100.0  100.0          100.0  ...  100.0          100.0
15  111.8          117.1  100.4           89.4  ...   90.8           79.9
16   71.2           69.1   59.5           50.9  ...   57.7           54.2
17   89.2           88.5   81.7           76.7  ...   75.2           70.2
18   60.9           58.7   55.0           53.2  ...   56.8           50.4
19   86.8           84.2   70.5           59.1  ...   64.7           60.4
20  101.3          103.0   97.9           88.1  ...   91.4           80.4
21   82.7           77.4   77.4           78.8  ...   78.7           74.7
22   58.5           57.4   49.7           44.2  ...   53.8           48.0
23   68.5           74.8   61.1           56.4  ...   57.1           44.1
24   54.9           53.3   45.2           39.5  ...   44.0           40.1
25   67.8           66.7   57.7           50.0  ...   54.9           50.8
26   63.9           63.5   62.6           58.1  ...   58.5           54.7
27   52.8           52.9   49.0           48.9  ...   50.0           45.5
28   61.3           59.3   51.2           44.2  ...   51.0           43.7
29   47.8           48.2   42.2           36.3  ...   34.2           31.5
30   55.3           54.0   42.8           41.3  ...   39.0           35.0
31   60.7           59.2   57.6           51.2  ...   59.0           55.2
32   58.6           57.9   48.0           42.5  ...   48.3           42.3
33   61.7           61.5   57.1           63.9  ...   56.2           50.4
34   51.4           49.5   42.5           36.5  ...   39.8           36.5
35   38.7           39.2    NaN            NaN  ...    NaN            NaN
36   30.5           31.0   29.7           30.2  ...   32.1           28.7
37   52.8           50.9   52.1           52.1  ...   55.8           53.6
38   49.5           47.9   44.5           32.6  ...   27.5           29.4
39   28.3           29.5   28.1           28.1  ...   29.7           27.4
40   45.6           40.5   38.2           30.6  ...   26.4           28.0

     2019  2019 Mid-Year   2020  2020 Mid-Year  2021 Mid-Year   2022  \
0    84.3           85.4   85.2           88.8           89.0   84.4
1    77.4           78.9   79.2           81.4           82.4   79.0
2    75.4           74.4   72.3           73.7           76.8   74.4
3    68.6           66.6   64.8           67.0           70.5   68.9
4    78.8           77.1   76.1           78.6           83.9   78.9
5    69.1           68.9   65.6           67.8           70.4   68.4
6    72.6           75.2   76.8           80.4           78.4   74.8
7    80.9           79.9   78.9           82.9           84.4   80.8
8    78.5           83.7   86.4           91.4           92.2   94.5
9    81.4           81.5   81.3           78.8           87.0   85.6
10   77.9           77.3   73.5           75.5           79.1   77.2
11   82.8           84.5   85.5           81.6           80.3   78.7
12   62.5           66.5   67.4           64.1           70.0   70.6
13   91.7           89.4   91.5           92.1           93.9   93.9
14  100.0          100.0  100.0          100.0          100.0  100.0
15   78.4           79.7   79.1           82.7           85.1   83.2
16   53.7           53.6   51.9           51.5           54.8   51.7
17   80.7           85.2   78.5           72.6           74.9   74.3
18   50.6           51.6   45.2           46.9           50.5   45.6
19   58.3           59.4   57.2           58.8           58.2   59.0
20   69.8           80.2   81.1           81.1           82.6   84.0
21   78.1           79.2   77.2           77.9           80.8   80.7
22   48.4           49.0   49.0           48.6           51.8   51.8
23   46.5           47.3   42.7           33.5           38.9   36.7
24   39.3           40.0   39.0           40.0           41.1   40.0
25   50.4           50.1   49.3           50.9           52.8   51.5
26   56.8           57.5   56.7           56.2           53.4   52.2
27   45.8           47.4   45.6           40.6           47.3   44.9
28   45.6           44.5   43.4           43.1           45.5   46.1
29   32.9           34.7   36.2           31.1           35.6   34.1
30   32.5           32.5   33.2           31.0           30.0   27.9
31   56.0           58.5   59.0           59.4           56.1   54.3
32   42.6           43.0   44.1           43.3           48.0   43.9
33   50.3           51.1   50.1           49.2           51.9   53.9
34   36.3           36.7   36.7           38.8           39.2   37.6
35   38.6           37.2    NaN           38.7           38.4   37.5
36   28.0           28.3   28.2           27.4           27.7   28.2
37   55.2           56.8   57.2           55.8           51.0   50.4
38   30.3           33.9   36.2           33.4           33.6   34.1
39   27.4           28.3   27.6           25.9           27.2   27.6
40   28.7           30.4   32.7           30.1           30.2   29.3

    2022 Mid-Year   2023
0            70.8   76.1
1            70.4   77.1
2            64.7   68.8
3            62.7   69.7
4            68.4   70.8
5            62.2   61.8
6            68.9   73.6
7            74.3   71.4
8            82.0   80.3
9            77.9   74.2
10           69.8   74.2
11           77.4   78.9
12           69.3   65.3
13           95.4   99.6
14          100.0  100.0
15           76.6   81.5
16           44.5   51.5
17           73.3   73.0
18           39.1   46.8
19           54.2   59.8
20           79.1   85.9
21           76.6   75.7
22           48.6   54.6
23           39.2   38.2
24           38.8   42.4
25           49.5   54.9
26           49.4   48.7
27           39.6   40.5
28           39.2   45.3
29           35.4   37.4
30           26.7   24.5
31           53.9   51.2
32           39.3   44.0
33           48.7   47.7
34           32.6   36.6
35           36.5   35.1
36           27.2   25.0
37           46.7   49.8
38           35.3   30.8
39           25.1   24.0
40           32.1   27.1

[41 rows x 24 columns]

In [22]:
df_save.to_csv('test.csv', index=False)